<?php

namespace App\Http\Controllers;

use App\Mail\ContactMail;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Mail;

class PublicController extends Controller
{
    public function benvenuto() {
        return view('Benvenuto');
    }

    public function chisiamo(){

        $dentisti = [
            ['nome'=>'Giorgio Benestante', 'ruolo'=>'Dentista', 'storia'=>'Giorgio Benestante nato a Parigi, ha svolto i suoi studi Odontoiatrici nel sud della francia ,trasferito in Italia decide di aprire il suo studio che divenne in pochi mesi uno dei più rinomati', 'img'=>'/img/dentista4.jpg'],
            ['nome'=>'Krosto Lumino', 'ruolo'=>'Assistente Dentista', 'storia'=>'Krosto Lumino nato a Parigi, ha svolto i suoi studi Odontoiatrici nel sud della francia ,trasferito in Italia decide di aprire il suo studio che divenne in pochi mesi uno dei più rinomati', 'img'=>'/img/dentista1.jpg'],
            ['nome'=>'Polosky acofie', 'ruolo'=>'Segretaria', 'storia'=>'Polosky acofie nato a Parigi, ha svolto i suoi studi Odontoiatrici nel sud della francia ,trasferito in Italia decide di aprire il suo studio che divenne in pochi mesi uno dei più rinomati', 'img'=>'/img/dentista3.jpg'],
            ['nome'=>'Naue Jkoea', 'ruolo'=>'Assistente Dentista', 'storia'=>'Naue Jkoea nato a Parigi, ha svolto i suoi studi Odontoiatrici nel sud della francia ,trasferito in Italia decide di aprire il suo studio che divenne in pochi mesi uno dei più rinomati', 'img'=>'/img/dentista2.jpg'],
            ['nome'=>'Imkaer Orsal', 'ruolo'=>'Dentista', 'storia'=>'Imkaer Orsal nato a Parigi, ha svolto i suoi studi Odontoiatrici nel sud della francia ,trasferito in Italia decide di aprire il suo studio che divenne in pochi mesi uno dei più rinomati', 'img'=>'/img/dentista5.jpg'],
            ['nome'=>'Erneslk Sokove', 'ruolo'=>'Dentista', 'storia'=>'Erneslk Sokove nato a Parigi, ha svolto i suoi studi Odontoiatrici nel sud della francia ,trasferito in Italia decide di aprire il suo studio che divenne in pochi mesi uno dei più rinomati', 'img'=>'/img/dentista6.jpg'],
        ];

        return view('chisiamo', ['dentisti'=>$dentisti]);

    }

    public function servizi(){

        $servizi = [
            ['nome'=>'Pulizia Dentale','img'=>'/img/servizio.jpg','descrizione'=>'Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum!!Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum!!'],
            ['nome'=>'Visita Odontoiatrica','img'=>'/img/servizio.jpg','descrizione'=>'Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum!!Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum!!'],
            ['nome'=>'Applicazione Apparecchio','img'=>'/img/servizio.jpg','descrizione'=>'Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum!!Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum!!'],
            ['nome'=>'Ricostruzione Denti','img'=>'/img/servizio.jpg','descrizione'=>'Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum!!Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum!!'],
            ['nome'=>'Pulizia Dentale','img'=>'/img/servizio.jpg','descrizione'=>'Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum!!Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum!!'],
            ['nome'=>'Rimozione Carie','img'=>'/img/servizio.jpg','descrizione'=>'Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum!!Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum!!'],
        ];

        return view('servizi', ['servizi'=>$servizi]);
    }

    public function scopri($nome){

        $servizi = [
            ['nome'=>'Pulizia Dentale','img'=>'/img/servizio.jpg','descrizione'=>'Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum!!Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum!!'],
            ['nome'=>'Visita Odontoiatrica','img'=>'/img/servizio.jpg','descrizione'=>'Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum!!Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum!!'],
            ['nome'=>'Applicazione Apparecchio','img'=>'/img/servizio.jpg','descrizione'=>'Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum!!Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum!!'],
            ['nome'=>'Ricostruzione Denti','img'=>'/img/servizio.jpg','descrizione'=>'Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum!!Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum!!'],
            ['nome'=>'Pulizia Dentale','img'=>'/img/servizio.jpg','descrizione'=>'Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum!!Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum!!'],
            ['nome'=>'Rimozione Carie','img'=>'/img/servizio.jpg','descrizione'=>'Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum!!Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum! Lorem ipsum dolor sit amet consectetur adipisicing elit. Esse sint adipisci iusto placeat aut temporibus eligendi soluta odit autem fuga. Ducimus eius tempora eaque nesciunt quidem dolorum, sequi odio cum!!'],
        ];

        foreach ($servizi as $servizio) {
            
            if ($servizio['nome'] == $nome) {
                

                return view('scopriservizi',['servizio'=>$servizio]);

            }
            
        }

    }

    public function prenota(){

        return view('prenota');

    }

    public function submit(Request $req){

        $user = $req->input('user');
        $message = $req->input('message');

        $email = $req->input('email');

        $contact = compact('user','message');


        Mail::to($email)->send(new ContactMail($contact));

        return redirect(route('Benvenuto'))->with('message','La tua richiesta è stata inoltrata, verrai ricontattato il prima possibile');
    }

}
